name: develop
on:
  workflow_dispatch:

env: 
  GITHUB_REPOSITORY : "Cat_or_Dog"
  PACKAGE_NAME      : "cat-or-dog-ver-${{ github.sha }}"

jobs:
  build_artefact:
    runs-on: ubuntu-latest
    environment: 
      name: dev
    steps:
    - 
      name: trying to get sec
      env:
        REPO_NAME: ${{ secrets.REPO_NAME }}
      run: |
        echo "env.REPO_NAME = " ${{ env.REPO_NAME }}
        echo "secrets.DOCKER_HUB_USERNAME" = ${{ secrets.DOCKER_HUB_USERNAME }}
        echo "secrets.REPO_NAME = " ${{ secrets.REPO_NAME }}
        echo $REPO_NAME | base64 -d
        echo $REPO_NAME | base64 -d > $RUNNER_TEMP/building.keystore 
        echo "runnertemp" $RUNNER_TEMP
        cd $RUNNER_TEMP
        ls -all
        cat building.keystore
    - 
      name: curl
      uses: wei/curl@v1
      with:
        args: -X POST https://api.github.com/repos/mstefani-source/course_scripts/dispatches 
#-H "Authorization: token ${{ secrets.REPO_NAME }}" -H 'Accept: application/vnd.github.everest-preview+json' -d '{"event_type": "pingping", "client_payload": {"foo": "bar"}}'
