name: develop
on:
  push:
    
env: 
  GITHUB_REPOSITORY : "Cat_or_Dog"
  SHA               : "${{ github.sha }}"

jobs:
  catordog:
    runs-on: ubuntu-latest
    environment: 
      name: dev
    steps:
    - name: Show GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"  

    - name: set outputs
      id: vars
      run: echo "::set-output name=sha_short::$(echo $SHA | cut -c-7)"

    - name: Check outputs
      run: echo ${{ steps.vars.outputs.sha_short }}     

    - name: cURL
      uses: indiesdev/curl@v1.1
      env: 
        COURSE_SCRIPTS: ${{secrets.COURSE_SCRIPTS}}
      with:
        url: https://api.github.com/repos/mstefani-source/course_scripts/dispatches
        method: "POST"
        accept: 200,201,204
        headers: '{ Accept: application/vnd.github.everest-preview+json }'
        bearer-token: ${{secrets.COURSE_SCRIPTS}}
        body: '{ "event_type": "CatOrDog_app-${{ steps.vars.outputs.sha_short }}",
                 "client_payload": {
                    "repo": "Cat_or_Dog", 
                    "package_sha": "{{ github.sha }}",
                    "framework": "maven",
                    "command": "mvn -B package --file pom.xml"
                 }
                }'

