name: Ku
on:
  push:

jobs:
  build_artefact:

    runs-on: ubuntu-latest

    steps:
    - 
      name: Checkout
      uses: actions/checkout@v3
    - 
      name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - 
      name: Build with Maven
      run: |
        mvn -B package --file pom.xml
        echo '::set-output name=SELECTED_COLOR::green'
    - 
      shell: bash
      run: |
        ls -all
        ls .. -all
    
    - 
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message:  gggggggggggg 
