name: develop
on:
  push:
    
env: 
  GITHUB_REPOSITORY : "Cat_or_Dog"
  PACKAGE_NAME      : "cat-or-dog-ver-${{ github.sha }}"

jobs:
  catordog:
    runs-on: ubuntu-latest
    environment: 
      name: dev
    steps:
    - name: cURL
      uses: indiesdev/curl@v1.1
      env: 
        COURSE_SCRIPTS: ${{secrets.COURSE_SCRIPTS}}
      with:
        url: https://api.github.com/repos/mstefani-source/course_scripts/dispatches
        method: "POST"
        accept: 200,201,204
        headers: '{ Accept: application/vnd.github.everest-preview+json }'
        bearer-token: ${{secrets.COURSE_SCRIPTS}}
        body: '{
                "event_type": "CatOrDog_app", 
                "client_payload": {
                    "package_sha": "${{ github.sha }}"
                 }
                }'

