name: dev/develop
on:
  push:

env: 
 GITHUB_REPOSITORY: Cat_or_Dog

jobs:
  build_artefact:
    runs-on: ubuntu-latest
    environment: repo
    steps:
    - name: trying to get sec
      env:
        REPO_NAME: ${{ secrets.REPO_NAME }}
      run: |
        echo $REPO_NAME | base64 -d
        echo $REPO_NAME | base64 -d > $RUNNER_TEMP/building.keystore 
        echo "runnertemp" $RUNNER_TEMP
        ls $RUNNER_TEMP -all
        cat $RUNNER_TEMP/building.keystore
    - 
      name: Checkout
      uses: actions/checkout@v3
    - 
      name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - 
      name: Build with Maven
      run: |
        mvn -B package --file pom.xml
        echo '::set-output name=SELECTED_COLOR::green'
    - 
      name: show environments
      shell: bash
      run: |
        echo =================1===================
        echo $GITHUB_REPOSITORY
        echo =================2===================
        echo "${{env.GITHUB_REPOSITORY}}" ${{env.GITHUB_REPOSITORY}}
        echo =================3===================
        env
